media: src/assets
content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: teaser, label: Teaser, type: text }
      - { name: category, label: Category, type: string }
      - { name: image, label: Image, type: image }
      - { name: description, label: Description, type: text }
      - { name: canonicalUrl, label: Canonical URL, type: string }
      - { name: section, label: Section, type: string }
      - { name: ogSiteName, label: OG Site Name, type: string }
      - { name: ogType, label: OG Type, type: string }
      - { name: ogUrl, label: OG URL, type: string }
      - { name: ogImageUrl, label: OG Image URL, type: image }
      - { name: ogImageWidth, label: OG Image Width, type: number }
      - { name: ogImageHeight, label: OG Image Height, type: number }
      - { name: ogImageAlt, label: OG Image Alt Text, type: string }
      - { name: ogImageType, label: OG Image Type, type: string }
      - { name: publishedDate, label: Published Date, type: date }
      - { name: modifiedDate, label: Modified Date, type: date }
      - { name: authorName, label: Author Name, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: customers
    label: Customers
    type: collection
    path: src/content/customers
    view:
      fields: [title, companyName, sort]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: color, label: Color, type: string }
      - { name: image, label: Image, type: image }
      - { name: headerLead, label: Header Lead, type: string }
      - { name: headerInfo, label: Header Info, type: text }
      - { name: headerImage, label: Header Image, type: image }
      - { name: contactName, label: Contact Name, type: string }
      - { name: contactTitle, label: Contact Title, type: string }
      - { name: contactImage, label: Contact Image, type: image }
      - { name: companyName, label: Company Name, type: string }
      - { name: companyIndustry, label: Company Industry, type: string }
      - { name: companyPeople, label: Company People, type: string }
      - { name: quote, label: Quote, type: text }
      - { name: sort, label: Sort Order, type: number }
      - { name: ogUrl, label: OG URL, type: string }
      - { name: ogSiteName, label: OG Site Name, type: string }
      - { name: ogType, label: OG Type, type: string }
      - { name: ogImageUrl, label: OG Image URL, type: image }
      - { name: ogImageWidth, label: OG Image Width, type: number }
      - { name: ogImageHeight, label: OG Image Height, type: number }
      - { name: ogImageAlt, label: OG Image Alt Text, type: string }
      - { name: ogImageType, label: OG Image Type, type: string }
      - { name: publishedDate, label: Published Date, type: date }
      - { name: modifiedDate, label: Modified Date, type: date }
      - { name: body, label: Body, type: rich-text }
  - name: templates
    label: Templates
    type: collection
    path: src/content/templates
    fields:
      - { name: body, label: Body, type: rich-text }
